### ISSUE TITLE
How to push to npm

### ISSUE THREAD

**Issue by julien-c** [moskalyk/typed-aws-lambda-mock-context#1]
Hi,

I was curious, how do you push this package (or other like it) to npm under the `@types` namespace?

Thanks!

**Comment by moskalyk** [comment]
Yeah the process was pretty straight forward. If you check out the repo https://github.com/DefinitelyTyped/DefinitelyTyped it has the instructions there. Basically you just make a pull request with you package ensuring that you've completed their TODOs. email me at morgan.moskalyk@gmail.com if you need help!

**Comment by julien-c** [comment]
Thanks! I've done this before, but I didn't know it now published automatically to `npm/@types`

I guess no more `typings` necessary!

Thanks
